## Numpy Array Operation

In [2]:
import numpy as np

In [6]:
arr_2d = np.array([[1,2,3],
                   [4,10,6],
                   [8,9,5]])

print(arr_2d[0,1])
print(arr_2d[:,1]) #column

2
[ 2 10  9]


## Sorting

In [10]:
print(arr_2d)
print(np.sort(arr_2d, axis=0))
print(np.sort(arr_2d, axis=1))

[[ 1  2  3]
 [ 4 10  6]
 [ 8  9  5]]
[[ 1  2  3]
 [ 4  9  5]
 [ 8 10  6]]
[[ 1  2  3]
 [ 4  6 10]
 [ 5  8  9]]


## Filter

In [14]:
numbers = np.array([1,2,3,4,5,6,7,8])
e_number = numbers[numbers%2 ==0]
print(e_number)

mask = numbers>5
print(mask)
print(numbers[mask])

[2 4 6 8]
[False False False False False  True  True  True]
[6 7 8]


## Indexing 

In [17]:
idx = [0,4,6]
print(numbers[idx])

np_where = np.where(numbers>5)
print(np_where)
print(numbers[np_where])

[1 5 7]
(array([5, 6, 7]),)
[6 7 8]


In [26]:
numbers2 = np.array([9,14,16,37])
combined = np.concatenate((numbers,numbers2))
print(combined)

[ 1  2  3  4  5  6  7  8  9 14 16 37]


## Array compatibility

In [36]:
print(numbers.shape == numbers2.shape)
numbers3 = np.array([10,11,12])
with_new_row = np.vstack((arr_2d, numbers3))
print(arr_2d,'\n')
print(with_new_row)

numbers3 = np.array([[10],[11],[12]])
with_new_col = np.hstack((arr_2d, numbers3))
print(arr_2d,'\n')
print(with_new_col)

False
[[ 1  2  3]
 [ 4 10  6]
 [ 8  9  5]] 

[[ 1  2  3]
 [ 4 10  6]
 [ 8  9  5]
 [10 11 12]]
[[ 1  2  3]
 [ 4 10  6]
 [ 8  9  5]] 

[[ 1  2  3 10]
 [ 4 10  6 11]
 [ 8  9  5 12]]
