## NUMPY ARRAY AND BASIC

In [1]:
import numpy as np

## CREATING ARRAY FROM LIST

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr_2d)

1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]]


## Numpy efficiency

In [3]:
import time
start = time.time()
list_comp = [i**2 for i in range(1000000)]
end = time.time()
print("List comprehension time:", end - start)

start = time.time()
np_array = np.arange(1000000)**2
end = time.time()
print("Numpy array time:", end - start)

List comprehension time: 0.11505556106567383
Numpy array time: 0.008587121963500977


## Creating array from scratch

In [5]:
zeros = np.zeros((3,5))
print(zeros)

ones = np.ones((3,5))
print(ones)

full = np.full((3,5),5)
print(full)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [8]:
random = np.random.random((2,3))
print(random)

sequence = np.arange(0,10,2)
print(sequence)


[[0.05602064 0.45906705 0.20246346]
 [0.9640746  0.54052707 0.77617851]]
[0 2 4 6 8]


## Reshaped array

In [13]:
arr = np.arange(12)
reshaped = arr.reshape((3,4))
print(arr)
print(reshaped)

flattend = reshaped.flatten()
print(flattend)

# return view
reveled = reshaped.ravel()
print(reveled)

transpose = reshaped.T
print(transpose)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
